name: CI Pipeline for Bookstore

# Triggers the pipeline on push and pull requests to the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Job to run linting and unit tests
  test:
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository code
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to latest version for better performance and security

      # Sets up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5  # Updated to latest version
        with:
          python-version: '3.13'

      # Installs dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

       # Runs all unit tests with coverage reporting
      - name: Run Unit Tests
        run: |
          pytest tests/ --junitxml=unit-results.xml
        continue-on-error: true  # Continues to upload results even if tests fail

      # Uploads test results as an artifact
      - name: Upload Unit Test Results
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: unit-results.xml
        if: always()  # Uploads results even on test failure

      # Uploads coverage report as an artifact
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
        if: always()  # Ensures coverage report is always uploaded
