name: CI Pipeline for Bookstore

# Triggers the pipeline on push and pull requests to the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Job to run tests and coverage
  test:
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Sets up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # Installs dependencies, including pytest-cov for coverage
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-cov # Add this line to install the coverage plugin

       # Runs all unit tests and generates coverage report
      - name: Run Unit Tests with Coverage
        run: |
          # The --cov flag generates a coverage report in XML format
          pytest tests/ --cov=. --cov-report=xml --junitxml=unit-results.xml
        continue-on-error: true

      # Uploads test results as an artifact
      - name: Upload Unit Test Results
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: unit-results.xml
        if: always()

      # New step to upload the coverage report
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml # Path to the generated coverage file
        if: always()
